version: "0.1"

phases:
  pre_build:
    commands:
      - npm i -g @angular/cli
      - npm install

  build:
    commands:
      - ng build --prod

artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  discard-paths: yes
